data_config:
  train_data:
      # Directory dataset
      dataset_name: air-quality-madrid
      dir: data/raw/air-quality-madrid/csvs_per_year/csvs_per_year


models:
  - model_name: TCN
    baseline: 
        experiment_name: baseline_model_tcn
        default_params_path: models/tcn/baseline_model_tcn_default_params.json
        output_dir: models/tcn
    hpo:
        experiment_name: hpo_model_tcn
        n_trials: 2
        default_params_path : models/tcn/hpo_model_tcn_default_params.json
        output_dir: models/tcn
    best_model:
        experiment_name: best_model_tcn
        default_params_path : models/tcn/hpo_model_tcn_default_params.json
        optimized_params_path: models/tcn/hpo_model_tcn_optimized_params.json
        output_dir: models/tcn

  - model_name: NBeats
    baseline: 
        experiment_name: baseline_model_nbeats
        default_params_path: models/nbeats/baseline_model_nbeats_default_params.json
        output_dir: models/nbeats
    hpo:
        experiment_name: hpo_model_nbeats
        n_trials: 2
        default_params_path : models/nbeats/hpo_model_nbeats_default_params.json
        output_dir: models/nbeats
    best_model:
        experiment_name: best_model_nbeats
        default_params_path : models/nbeats/hpo_model_nbeats_default_params.json
        optimized_params_path: models/nbeats/hpo_model_nbeats_optimized_params.json
        output_dir: models/nbeats

outputs:
  raw_dir: "data/raw"
  prepro_dir: "data/prepro"
  #models_dir: "models"

